
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 24 11:26:08 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 23;
  public static final int READ = 5;
  public static final int INCR = 17;
  public static final int IDENT = 28;
  public static final int PLUS = 19;
  public static final int RBRACE = 16;
  public static final int RPAREN = 12;
  public static final int EQUAL = 24;
  public static final int CHAR = 25;
  public static final int RETURN = 3;
  public static final int RANGLE = 14;
  public static final int DECR = 18;
  public static final int LPAREN = 11;
  public static final int LBRACE = 15;
  public static final int SEMIC = 9;
  public static final int COMMA = 8;
  public static final int LANGLE = 13;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int DIV = 22;
  public static final int PROG = 2;
  public static final int MINUS = 20;
  public static final int CONST = 6;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int NEW = 7;
  public static final int BOOL = 26;
  public static final int MUL = 21;
  public static final int VOID = 10;
}

